name: Playwright Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  playwright_tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: unopim
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, bcmath
          tools: composer:v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Install Node.js dependencies
        run: npm install

      - name: Install Playwright Chromium only
        run: |
          npx playwright install-deps chromium
          npx playwright install chromium

      - name: Generate application key & migrate
        run: |
          php artisan key:generate
          php artisan migrate --force
          php artisan db:seed --force || true

      - name: Start Laravel server
        run: php artisan serve --host=127.0.0.1 --port=8000 &
      
      - name: Wait for Laravel to be ready
        run: npx wait-on http://127.0.0.1:8000

      - name: Run Playwright tests
        run: npx playwright test
