name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  playwright:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: unopim
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Setup environments ---
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, bcmath
          tools: composer:v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # --- Install dependencies ---
      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Install Node dependencies
        run: npm install

      - name: Install Playwright Chromium
        run: npx playwright install chromium --with-deps

      # --- Laravel setup ---
      - name: Create .env
        run: |
          cp .env.example .env || touch .env
          echo "APP_ENV=local" >> .env
          echo "APP_KEY=" >> .env
          echo "APP_DEBUG=true" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=unopim" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env

      - name: Generate key & migrate
        run: |
          php artisan key:generate --force
          php artisan migrate --force

      # --- Start Laravel server for Playwright ---
      - name: Start Laravel server
        run: php artisan serve --host=127.0.0.1 --port=8000 > laravel.log 2>&1 &
      
      - name: Wait for server to be ready
        run: npx wait-on http://127.0.0.1:8000

      # --- Run Playwright tests ---
      - name: Run Playwright tests
        run: npx playwright test --config=playwright.config.ts --reporter=html --trace on

      # --- Upload test report ---
      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
