name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  playwright_tests:
    name: Playwright End-to-End UI Tests
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php-version: ['8.2']
        node-version: ['18']

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: unopim
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, fileinfo, gd, intl, mbstring, openssl, pdo, pdo_mysql, tokenizer, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Install PHP Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Configure Environment
        run: |
          cp .env.example .env
          sed -i "s|APP_ENV=.*|APP_ENV=testing|" .env
          sed -i "s|DB_HOST=.*|DB_HOST=127.0.0.1|" .env
          sed -i "s|DB_PORT=.*|DB_PORT=${{ job.services.mysql.ports[3306] }}|" .env
          sed -i "s|DB_DATABASE=.*|DB_DATABASE=unopim|" .env
          sed -i "s|DB_USERNAME=.*|DB_USERNAME=root|" .env
          sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=root|" .env
          cat .env

      - name: Install & Migrate Database
        run: |
          php artisan unopim:install --skip-env-check --skip-admin-creation
          php artisan migrate:fresh --seed
          php artisan serve --host=0.0.0.0 --port=8000 &
      
      - name: Wait for Application
        run: npx wait-on http://localhost:8000

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          # Try multiple possible lockfile locations, but ignore if missing
          cache-dependency-path: |
            package-lock.json
            tests/e2e-pw/package-lock.json

      - name: Install Playwright & Run Tests
        working-directory: tests/e2e-pw
        run: |
          npm ci || npm install
          npx playwright install --with-deps
          npx playwright test --reporter=line

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/e2e-pw/playwright-report
