name: Playwright Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  playwright_tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: unopim
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cache Composer deps
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, fileinfo, gd, intl, mbstring, openssl, pdo, pdo_mysql, tokenizer, zip
          tools: composer:v2

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Setup Environment
        run: |
          cp .env.example .env
          sed -i "s|APP_ENV=.*|APP_ENV=testing|" .env
          sed -i "s|DB_HOST=.*|DB_HOST=127.0.0.1|" .env
          sed -i "s|DB_PORT=.*|DB_PORT=3306|" .env
          sed -i "s|DB_DATABASE=.*|DB_DATABASE=unopim|" .env
          sed -i "s|DB_USERNAME=.*|DB_USERNAME=root|" .env
          sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=root|" .env
          cat .env

      - name: Run Database Migrations
        run: php artisan migrate:fresh --seed

      - name: Start Laravel Server
        run: php artisan serve --host=127.0.0.1 --port=8000 > /dev/null 2>&1 &

      - name: Wait for Laravel to start
        run: npx wait-on http://127.0.0.1:8000

      # Cache npm
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            tests/e2e-pw/node_modules
          key: npm-${{ hashFiles('tests/e2e-pw/package-lock.json') }}
          restore-keys: npm-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Playwright Dependencies
        working-directory: tests/e2e-pw
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright Tests
        working-directory: tests/e2e-pw
        run: npx playwright test --reporter=list

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/e2e-pw/playwright-report
