name: Playwright Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  playwright_tests:
    name: Playwright End-to-End UI Test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['8.2']

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: unopim
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, fileinfo, gd, intl, mbstring, openssl, pdo, pdo_mysql, tokenizer, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Set environment variables
        run: |
          cp .env.example .env
          sed -i "s/^APP_ENV=.*/APP_ENV=testing/" .env
          sed -i "s/^DB_HOST=.*/DB_HOST=127.0.0.1/" .env
          sed -i "s/^DB_PORT=.*/DB_PORT=${{ job.services.mysql.ports[3306] }}/" .env
          sed -i "s/^DB_DATABASE=.*/DB_DATABASE=unopim/" .env
          sed -i "s/^DB_USERNAME=.*/DB_USERNAME=root/" .env
          sed -i "s/^DB_PASSWORD=.*/DB_PASSWORD=root/" .env
          cat .env

      - name: Run UnoPim installer & migrations
        run: |
          php artisan unopim:install --skip-env-check --skip-admin-creation
          php artisan migrate --force
          php artisan migrate:fresh --seed
          nohup php artisan serve --host=0.0.0.0 --port=8000 > server.log 2>&1 &

      - name: Wait for UnoPim to be ready
        run: npx wait-on http://localhost:8000

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Playwright and run tests
        run: |
          cd tests/e2e-pw
          npm ci
          npx playwright install --with-deps
          npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/e2e-pw/playwright-report
